### ISSUE TITLE
Console Logging

### ISSUE THREAD

**Issue by genericandy** [EFForg/privacybadgerchrome#567]
Could you please add an option to disable the Privacy Badger console logging? I use the console for debugging my web development projects & the Privacy Badger console logs pile up. Specifically it is line 24 of clobbercookie.js:

chrome.runtime.sendMessage({checkLocation:document.location}, function(blocked) {
  if (blocked) {
    console.log('clobbering cookies for', document.location);

**Comment by SwartzCr** [comment]
I can probably just get rid of that line, I don't think we should ever need to write to the general chrome console

**Comment by cooperq** [comment]
fixed in #581

**Comment by genericandy** [comment]
I am still seeing this issue. It is the Cookie Getter.
![cookies](https://cloud.githubusercontent.com/assets/5195231/11069349/4cad40ac-879b-11e5-804b-0da0fc0bf08b.png)

**Comment by genericandy** [comment]
This issue still persists. See below. This is just from visiting a tumblr page with a youtube video.

![cookies](https://cloud.githubusercontent.com/assets/5195231/11069404/8cc95400-879b-11e5-8bc5-cc7223db5305.png)

**Comment by cooperq** [comment]
Fixed! https://github.com/EFForg/privacybadgerchrome/wiki/Help-test-Privacy-Badger-for-chrome
