### ISSUE TITLE
Privacy Badger broken on Chrome Dev

### ISSUE THREAD

**Issue by ajthemacboy** [EFForg/privacybadgerchrome#901]
Privacy Badger is reported as 'corrupt' on Chrome Dev (my exact version was 54.0.2837.0 dev-m (64 bit)) but works fine on the stable channel. I've tested on two different browsers. I have not tested the Beta or Canary channels. Clicking "Repair" reinstalls the extension with the same error.

This does not occur with any other extensions.

This occurs even when "Extension content verification" is set to Bootstrap in chrome://flags. 

This issue also occurs with HTTPS Everywhere and has been reported on its GitHub as well.

**Comment by cowlicks** [comment]
I can reproduce this.

**Comment by cowlicks** [comment]
I suppose this could be the problem, from [this chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=389879):

> ... downloading additional files to use in the extension that are placed in some new place should be fully supported. But self-modification of files that came in the original .crx cannot be.

**Comment by cowlicks** [comment]
I can't find a way to debug this so its pretty opaque. 

Privacy Badger does not use the filesystem api so I don't see how it could be changing its own files.

I don't think it is this zero length files bug because I couldn't find any zero length files.

https://bugs.chromium.org/p/chromium/issues/detail?id=399251#makechanges

**Comment by cowlicks** [comment]
Maybe we are violating the default [Content Security Policy](https://developer.chrome.com/extensions/contentSecurityPolicy) we get by having `"manifest_version": 2`. I'm not even sure if this would cause the error we are seeing though. Basically we:
* Can't use eval (but I don't think we do)
* Can't use inline js (but I don't think we do)
* Can only use local scripts, and object resources. (I think we do this)

But these rules don't apply to content scripts. Maybe I missed something.

**Comment by ajthemacboy** [comment]
See https://github.com/EFForg/https-everywhere/issues/5874

**Comment by josh-berry** [comment]
I am seeing this in Chrome Beta as well (53.0.2785.80 beta (64-bit)), on MacOS El Capitan (10.11.6), with Privacy Badger 2016.08.29.

Notably, I do NOT see the same issue with HTTPS Everywhere.

**Comment by cooperq** [comment]
This is now fixed as of #731b76a80c88d029430540097a5a6e347a081eda

**Comment by MikeN123** [comment]
Settings extension content verification to 'enforce' unfortunately doesn't fix the issue for me.

**Comment by cooperq** [comment]
So it turns out this is an issue in chrome, the chrome devs are aware of it and are working on a fix now. Follow the issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=643814
